version: "3.8"

services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./packages/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/frontend:/usr/src/app
      - /usr/src/app/node_modules
